version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./certs:/certs
    ports:
      - "8000:8000"
    environment:
      ADDR: '192.168.11.30'
      PORT: '8000'
    command: ["python", "main.py"]